// Generated by https://quicktype.io

interface ElementInfo {
  type: string;
  innerText?: string,
  id?: string;
  class?: string[];
  attributes?: { [key: string]: string };
  children?: ElementInfo[];
  repeat?: number;
}
